// This file is automatically generated. DO NOT EDIT

import type { Result, CheckConfig, CheckProgress, Judge, ScrapeSource, AppSettings, ResultFilter } from '../../../src/types'

export function ClearResults(): Promise<void>;
export function ExportProxyList(arg1: string[], arg2: string): Promise<void>;
export function ExportResults(arg1: string, arg2: ResultFilter, arg3: string): Promise<void>;
export function GetCheckProgress(): Promise<CheckProgress>;
export function GetIP(): Promise<string>;
export function GetJudges(): Promise<Judge[]>;
export function GetResults(arg1: ResultFilter): Promise<Result[]>;
export function GetSettings(): Promise<AppSettings>;
export function GetSources(): Promise<ScrapeSource[]>;
export function OpenFileDialog(): Promise<string>;
export function ReadFile(arg1: string): Promise<string>;
export function OpenSaveDialog(arg1: string): Promise<string>;
export function SaveJudges(arg1: Judge[]): Promise<void>;
export function SaveSettings(arg1: AppSettings): Promise<void>;
export function SaveSources(arg1: ScrapeSource[]): Promise<void>;
export function StartChecking(arg1: string[], arg2: CheckConfig): Promise<void>;
export function StartScraping(arg1: string[]): Promise<void>;
export function StopChecking(): Promise<void>;
export function StopScraping(): Promise<void>;
export function TestJudge(arg1: string): Promise<{ alive: boolean; latencyMs: number }>;
