// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearResults() {
  return window['go']['main']['App']['ClearResults']();
}

export function ExportProxyList(arg1, arg2) {
  return window['go']['main']['App']['ExportProxyList'](arg1, arg2);
}

export function ExportResults(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportResults'](arg1, arg2, arg3);
}

export function GetCheckProgress() {
  return window['go']['main']['App']['GetCheckProgress']();
}

export function GetIP() {
  return window['go']['main']['App']['GetIP']();
}

export function GetJudges() {
  return window['go']['main']['App']['GetJudges']();
}

export function GetResults(arg1) {
  return window['go']['main']['App']['GetResults'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSources() {
  return window['go']['main']['App']['GetSources']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function OpenSaveDialog(arg1) {
  return window['go']['main']['App']['OpenSaveDialog'](arg1);
}

export function SaveJudges(arg1) {
  return window['go']['main']['App']['SaveJudges'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveSources(arg1) {
  return window['go']['main']['App']['SaveSources'](arg1);
}

export function StartChecking(arg1, arg2) {
  return window['go']['main']['App']['StartChecking'](arg1, arg2);
}

export function StartScraping(arg1) {
  return window['go']['main']['App']['StartScraping'](arg1);
}

export function StopChecking() {
  return window['go']['main']['App']['StopChecking']();
}

export function StopScraping() {
  return window['go']['main']['App']['StopScraping']();
}

export function TestJudge(arg1) {
  return window['go']['main']['App']['TestJudge'](arg1);
}
