// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function ClearResults():Promise<void>;

export function ExportProxyList(arg1:Array<string>,arg2:string):Promise<void>;

export function ExportResults(arg1:string,arg2:core.ResultFilter,arg3:string):Promise<void>;

export function GetCheckProgress():Promise<core.CheckProgress>;

export function GetIP():Promise<string>;

export function GetJudges():Promise<Array<core.Judge>>;

export function GetResults(arg1:core.ResultFilter):Promise<Array<core.Result>>;

export function GetSettings():Promise<core.AppSettings>;

export function GetSources():Promise<Array<core.ScrapeSource>>;

export function OpenFileDialog():Promise<string>;

export function OpenSaveDialog(arg1:string):Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function SaveJudges(arg1:Array<core.Judge>):Promise<void>;

export function SaveSettings(arg1:core.AppSettings):Promise<void>;

export function SaveSources(arg1:Array<core.ScrapeSource>):Promise<void>;

export function StartChecking(arg1:Array<string>,arg2:core.CheckConfig):Promise<void>;

export function StartScraping(arg1:Array<string>):Promise<void>;

export function StopChecking():Promise<void>;

export function StopScraping():Promise<void>;

export function TestJudge(arg1:string):Promise<Record<string, any>>;
